package com.contextflow.placement.domain;

public enum PlacementItemType {
    SCENE_DIALOGUE_CHOICE,
    CONTEXT_MEANING,
    POLITENESS_JUDGMENT,
    LISTENING_COMPREHENSION,
    EXPRESSION_COMPLETION,
    INTENT_UNDERSTANDING,
    TRUE_FALSE,
    SYNONYM_CHOICE,
    ANTONYM_CHOICE,
    CLOZE_TEXT
}
